Tourist Talk/TouristTalk/TouristTalk/Models/ViewModel/ConversationViewModel.cs
using System.Collections.Generic;
using System;
using System.Web;
using System.ComponentModel.DataAnnotations;
using TouristTalk.Validation;
using TouristTalk.Exceptions;

namespace TouristTalk.Models
{
    /// <summary>
    /// Used to hold display data items for conversation view
    /// Acts as conduit between conversation view and conversation model.
    /// </summary>
    public class ConversationViewModel
    {
        public int ConversationID { get; set; }
        public string Title { get; set; }
        public string OtherUser { get; set; }
        public string CurrentUser { get; set; }
        public DateTime StartTime { get; set; }
        public string InstigatorName { get; set; }  //who started the conversation
        [ScaffoldColumn(false)]
        public List<MessageModel> Messages { get; set; }
        public int CurrentUserID { get; protected set; }

        [Display(Name = "Message")]
        public string NewMessageText { get; set; }       
        
        [AllowedFileType] //limits file types, custom attribute
        public HttpPostedFileBase File { get; set; }
       
        //Initialiser can not be deleted as used in binding model to view
        public ConversationViewModel() { }

        /// <summary>
        ///  Initialises class, gets conversation data to be displayed in view
        /// </summary>
        /// <param name="conversation"></param>
        public ConversationViewModel(ConversationModel conversation)
        {
            try
            {                
                ConversationID = conversation.ID;
                Title = conversation.Title;
                OtherUser = conversation.OtherUser.UserName;
                CurrentUser = conversation.CurrentUser.UserName;
                StartTime = conversation.StartTime;
                InstigatorName = conversation.InstigatorName;
                Messages = conversation.Messages;
                CurrentUserID = conversation.CurrentUser.UserID;
            }
            catch (Exception e)
            {
                throw new TouristTalkException("Error while initialising ConversationViewModel", e);
            }
        }
    }
}

Tourist Talk/TouristTalk/TouristTalk/Models/ViewModel/MessageViewModel.cs
namespace TouristTalk.Models
{
    /// <summary>
    /// Model for Message View
    /// Acts as conduit between view and Message model.
    /// </summary>
    public class MessageViewModel
    {
        public MessageModel Message { get; protected set; }
        public string Align { get; protected set; }

        public string UserName { get; protected set; } 
        public string BackgroundColour { get; protected set; }

        /// <summary>
        /// Initialises class, sets whether messages should be displayed on
        /// left or right depending on if current user
        /// </summary>
        /// <param name="message">message details</param>
        /// <param name="conversation">conversation details</param>
        public MessageViewModel(MessageModel message, ConversationViewModel conversation)
        {
            Message = message;
            if (conversation.CurrentUserID == message.SenderID)
            {
                Align = "margin-left:0; margin-right:auto;";
                UserName = conversation.CurrentUser;
                BackgroundColour = "gainsboro";
            }
            else
            {
                Align = "margin-left:auto; margin-right:0;";
                UserName = conversation.OtherUser;
                BackgroundColour = "cornsilk";
            }
        }
    }
}

Tourist Talk/TouristTalk/TouristTalk/Models/ViewModel/MyConversationsViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TouristTalk.Models
{
    /// <summary>
    /// Model for MyConversations View
    /// </summary>
    public class MyConversationsViewModel
    {
        [ScaffoldColumn(false)]
        public List<ConversationModel> ConversationList { get; protected set; }

        /// <summary>
        /// Initialises class
        /// Gets all conversation details by invoking conversationList
        /// </summary>
        public MyConversationsViewModel()
        {
            ConversationListModel conversationList = new ConversationListModel();
            ConversationList = conversationList.ConversationList;
        }
    }
}

Tourist Talk/TouristTalk/TouristTalk/Controllers/ConversationController.cs
using System;
using System.Web.Mvc;
using TouristTalk.Models;
using TouristTalk.Validation;

namespace TouristTalk.Controllers
{
    /// <summary>
    /// Controller for all Conversation related screens
    /// </summary>
    public class ConversationController : Controller
    {
        /// <summary>
        /// Displays page of all user conversations. 
        /// </summary>
        /// <returns>screen of user conversations</returns>
        [AuthorizeUser]
        public ActionResult MyConversations()
        {
            try
            {
                //Gets all conversations for user and populates view model
                MyConversationsViewModel model = new MyConversationsViewModel();

                return View(model);
            }
            catch (Exception e)
            {
                return RedirectToAction("HandledCodeError", "ErrorHandler", new { exception = e.ToString() });
            }
        }

        /// <summary>
        /// Screen for adding (starting) conversation
        /// </summary>
        /// <returns>form for adding conversation</returns>
        [AuthorizeUser]
        public ActionResult Create()
        {
            try
            {
                //Get all Tour Agents that can be selected
                TourAgentModel tourAgent = new TourAgentModel();

                //Create View data
                CreateConversationViewModel model = new CreateConversationViewModel(tourAgent.AllAgents);

                return View(model);
            }
            catch (Exception e)
            {
                return RedirectToAction("HandledCodeError", "ErrorHandler", new { exception = e.ToString() });
            }
        }

        /// <summary>
        /// Action for recieving create conversation data
        /// </summary>
        /// <param name="model">data of conversation to be added</param>
        /// <returns>adds conversation then redirects to the created conversation</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeUser]
        public ActionResult Create(CreateConversationViewModel model)
        {
            try
            {
                TourAgentModel tourAgent = new TourAgentModel(model.TravelAgentID);

                if (tourAgent.ValidAgent)
                {
                    ConversationModel conversation = new ConversationModel(tourAgent, model.Title);
                    return RedirectToAction("Conversation", "Conversation", new { id = conversation.ID });
                }

                return RedirectToAction("LogOff", "Account");
            }
            catch (Exception e)
            {
                return RedirectToAction("HandledCodeError", "ErrorHandler", new { exception = e.ToString() });
            }
           
        }

        /// <summary>
        /// For displaying a conversation and all its messages and facility to add message
        /// </summary>
        /// <param name="id">conversation id</param>
        /// <returns>conversation screen</returns>
        [AuthorizeUser]
        public ActionResult Conversation(int id)
        {
            try
            {
                //get conversation data
                ConversationModel conversation = new ConversationModel(id);

                //initiate view model data
                ConversationViewModel model = new ConversationViewModel(conversation);
                return View(model);
            }
            catch (Exception e)
            {
                return RedirectToAction("HandledCodeError", "ErrorHandler", new { exception = e.ToString() });
            }
        }

        /// <summary>
        /// For recivieving post of new message to add to conversation
        /// </summary>
        /// <param name="model">new message data</param>
        /// <returns>conversation screen with new message added</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeUser]
        public ActionResult Conversation(ConversationViewModel model)
        {
            try
            {
                //get conversation data
                ConversationModel conversation = new ConversationModel(model.ConversationID);
                
                if (!ModelState.IsValid)
                {
                    model.Messages = conversation.Messages;
                    return View(model);
                }

                //Add message to conversation
                conversation.AddMessage(model.NewMessageText, model.File);

                //initiate view model data
                model = new ConversationViewModel(conversation);

                return RedirectToAction("Conversation", "Conversation", model.ConversationID);
            }
            catch (Exception e)
            {
                return RedirectToAction("HandledCodeError", "ErrorHandler", new { exception = e.ToString() });
            }                   
        }
    }
}

Tourist Talk/TouristTalk/TouristTalk/Controllers/MediaFileController.cs
using System;
using System.Web.Mvc;
using TouristTalk.Models;
using TouristTalk.Validation;

namespace TouristTalk.Controllers
{
    /// <summary>
    /// Controller for returning media files
    /// </summary>
    public class MediaFileController : Controller
    {
        /// <summary>
        /// Returns media file. Note throws an exception if file not for user
        /// </summary>
        /// <param name="fileID"><ID of file to be returned/param>
        /// <returns>media file</returns>
        [AuthorizeUser]
        public ActionResult GetMediaFile(int fileID)
        {
            try
            {
                MessageFileModel file = new MessageFileModel(fileID, SessionHandler.UserDetails.UserID);
                return File(file.Data, file.FileType);
            }
            catch (Exception e)
            {
                return RedirectToAction("HandledCodeError", "ErrorHandler", new { exception = e.ToString() });
            }
        }
    }
}

Tourist Talk/TouristTalk/TouristTalk/Views/Conversation/Conversation.cshtml
@using TouristTalk.Models;
@model TouristTalk.Models.ConversationViewModel

@{
    ViewBag.Title = "Conversation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 align="center">@Model.Title</h1>
<h3 align ="center">Conversation with @Model.OtherUser</h3>
<h3 align ="center">Started at @Model.StartTime by: @Model.InstigatorName</h3>


<div class="row">
    @foreach (MessageModel message in Model.Messages)
    {
        @Html.Partial("Message", new MessageViewModel(message, Model))
    }

    @Html.Partial("NewMessage", Model)
</div>

Tourist Talk/TouristTalk/TouristTalk/Views/Conversation/Create.cshtml
@model TouristTalk.Models.CreateConversationViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Create", "Conversation", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.TravelAgentID, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.TravelAgentID, Model.Names)
                        @Html.ValidationMessageFor(m => m.TravelAgentID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            }
        </section>
    </div>
</div>

Tourist Talk/TouristTalk/TouristTalk/Views/Conversation/Message.cshtml
@model TouristTalk.Models.MessageViewModel
<div style="background-color:@Model.BackgroundColour ;
     color:black;padding:20px;width: 600px;
     @Model.Align">
    <h4 ">@Model.UserName at @Model.Message.MessageTime</h4>
    <h3>@Model.Message.Text</h3>
    @if (@Model.Message.FileType != String.Empty && @Model.Message.FileType.Substring(0, 5) == "image")
    {
        <img src="@Url.Action("GetMediaFile", "MediaFile", new { fileID = Model.Message.FileID } )"
             width="480" height="400">
    }
    @if (Model.Message.FileType != String.Empty && Model.Message.FileType.Substring(0, 5) == "video")
    {
        <video id="videoPlay" width="480" height="400" controls>
            <source src="@Url.Action("GetMediaFile", "MediaFile", new { fileID = Model.Message.FileID } )" />
        </video>
    }
    @if (Model.Message.FileType != String.Empty && Model.Message.FileType.Substring(0, 5) == "audio")
    {
        <audio controls>
            <source src="@Url.Action("GetMediaFile", "MediaFile", new { fileID = Model.Message.FileID } )">
            Your browser does not support the audio tag.
        </audio>
    }
</div>
<br />

Tourist Talk/TouristTalk/TouristTalk/Views/Conversation/MyConversations.cshtml
@model TouristTalk.Models.MyConversationsViewModel
@using TouristTalk.Models
@{
    ViewBag.Title = "MyConversations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>MyConversations</h2>

<table class="table">
    <tr>
        <th>Correspondent</th>
        <th>Title</th>
        <th>Start Time</th>
        <th></th>
    </tr>

    @foreach (ConversationModel conversation in Model.ConversationList)
    {
        <tr>
            <td>@conversation.OtherUser.UserName</td>
            <td>@conversation.Title</td>
            <td>@conversation.StartTime</td>
            <td>@Html.ActionLink("Go To", "Conversation", new { id = conversation.ID })</td>
        </tr>
    }
</table>

Tourist Talk/TouristTalk/TouristTalk/Views/Conversation/NewMessage.cshtml
@model TouristTalk.Models.ConversationViewModel

<div style="background-color:IndianRed;
     color:black;padding:20px;width: 1100px;">
    <section id="messageForm">
        @using (Html.BeginForm("Conversation", "Conversation", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
            {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.ConversationID)
            <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.NewMessageText, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.NewMessageText, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.NewMessageText, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.File, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.File, new { type = "file", @class = "input-file" })
                        @Html.ValidationMessageFor(m => m.File, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Send" class="btn btn-default" />
                    </div>
                </div>
        }
    </section>
</div>